### ISSUE TITLE
Look into naming in IPC for slot_callback, the name is not very clear.

### ISSUE THREAD

**Issue by omarhogni** [Skaginn3x/framework#19]
just a thought maybe we should call this `bool_recv_recurrent` ?
and add aliases for shared ptr by postfixing with `_ptr`

_Originally posted by @jbbjarnason in https://github.com/Skaginn3x/framework/pull/17#discussion_r1152966478_

**Comment by jbbjarnason** [comment]
Suggestion on namings:
- signal = publisher/sender
- slot = receiver
- slot_callback = subscriber
- slot_configurable = connector

**Comment by omarhogni** [comment]
@jbbjarnason can this be closed?
