### ISSUE TITLE
Rewrite tfc::ec::devices::get to utilize compile time lists

### ISSUE THREAD

**Issue by omarhogni** [Skaginn3x/framework#20]
later we should add devices to mp::list https://github.com/boost-ext/mp and then this function would iterate over defined types

_Originally posted by @jbbjarnason in https://github.com/Skaginn3x/framework/pull/17#discussion_r1153040855_

**Comment by jbbjarnason** [comment]
done here https://github.com/Skaginn3x/framework/pull/81
