### ISSUE TITLE
minimum limit in ipc dbus api of double is weird

### ISSUE THREAD

**Issue by jbbjarnason** [Skaginn3x/framework#246]
![image](https://github.com/Skaginn3x/framework/assets/15651464/eec370a5-3e69-46fd-b90b-59c552c290c6)

Double can be below zero

**Comment by omarhogni** [comment]
`std::numeric_limits<double>::min()` seems to return a constant `DBL_MIN minimum normalized positive value of float, double and long double respectively` see https://en.cppreference.com/w/cpp/types/climits for climits header. Our use case can use `lowest` which is defined as we expect. see https://en.cppreference.com/w/cpp/types/numeric_limits/lowest
