### ISSUE TITLE
[ethercat] NPR Nominal motor power

### ISSUE THREAD

**Issue by omarhogni** [Skaginn3x/framework#255]
50 hectowatts configured in tfc which should be 5kw are actually 0.5kw in the drive. This causes issues. Have to look into the hectowatt conversion.

**Comment by jbbjarnason** [comment]
Is this MP units error or logic on our side?

**Comment by omarhogni** [comment]
I believe I just messed up the definition for the field. It is defined in hectowatts in tfc but should propably be defined as deciwatts.
I am gonna change this and test tomorrow with a physical drive.
