### ISSUE TITLE
Fix ethercat systemd file to handle startup

### ISSUE THREAD

**Issue by jbbjarnason** [Skaginn3x/framework#266]
Current systemd file does not successfully run ethercat because the executable does not find slaves on bootup, we need to investigate what target we can require to successfully start ethercat daemon

**Comment by omarhogni** [comment]
#269 starts this work. Missing a better target for knowing when the ipc-ruler is started and the network interface is ready for usage.

**Comment by jbbjarnason** [comment]
This has been addressed in couple of pull request, will remake issue when needed.
