### ISSUE TITLE
Min and max items of json array not strict

### ISSUE THREAD

**Issue by jbbjarnason** [Skaginn3x/framework#303]
example

![image](https://github.com/Skaginn3x/framework/assets/15651464/7e6be703-7392-4447-80d4-7723aa8552de)

![image](https://github.com/Skaginn3x/framework/assets/15651464/dd31e235-443d-47a3-b2d1-f0edfb977b89)

**Comment by SindriTh** [comment]
#311 addresses this issue on the frontend, enhancing the user experience by limiting the item count. However, I strongly recommend implementing similar validation on the backend as well. It's important to note that frontend validation primarily serves user experience purposes and does not ensure data integrity
