### ISSUE TITLE
array of item description not shown

### ISSUE THREAD

**Issue by omarhogni** [Skaginn3x/framework#351]
When working with arrays of items the description designated for that array is nowhere to be found.

**Comment by SindriTh** [comment]
Could you provide a sample array, along with screenshots?

**Comment by omarhogni** [comment]
When arrays are configured with a description the description is not visible anywhere.
![Screenshot from 2024-01-31 16-35-42](https://github.com/Skaginn3x/framework/assets/70097935/0fc10002-ad5a-4fef-8d2e-f5b5996d577f)

Expected description string
![Screenshot from 2024-01-31 16-38-56](https://github.com/Skaginn3x/framework/assets/70097935/10376c64-cbb4-4806-a1bc-908ee578f3c9)

The description text appears to follow the type decleration
```json
      "infeed_chain_to_sorter": {
        "$ref": "#/$defs/std::vector<tfc::observable<std::variant<std::monostate,printing_motor,atv320>>>",
        "description": "Infeed conveyors before the sorter"
      }
```

See for config.
[config_example.json](https://github.com/Skaginn3x/framework/files/14114578/config_example.json)

**Comment by omarhogni** [comment]
Another issue with this same config the website cannot render std::size_t we can create another issue if you want but the config structure is the same as here.
![image](https://github.com/Skaginn3x/framework/assets/70097935/e7178e21-3dcd-4d2f-a75a-f2369a66657b)

**Comment by SindriTh** [comment]
Do we want Array descriptions to show below the title:
![image](https://github.com/Skaginn3x/framework/assets/70705172/8ac3fa03-3863-4bac-89a6-5db70f26b560)

or on hover like shown in "sec"?:
![image](https://github.com/Skaginn3x/framework/assets/70705172/161dbd23-ca7c-4594-b6cb-eb6e1fe53e22)

@omarhogni
