### ISSUE TITLE
[cockpit] ascending/descending order of items

### ISSUE THREAD

**Issue by magni-mar** [Skaginn3x/framework#354]
Would be nice to have elements in cockpit sorted by ascending/descending numbers, letters and such in the Configurator.

![image](https://github.com/Skaginn3x/framework/assets/135731785/c516822a-755e-4baa-98d8-8b271c00f38b)

**Comment by SindriTh** [comment]
This is currently being sorted alphabetically, I can split the string in such a way that it has "atv320_i" which is sorted alphabetically, then "6", "7" etc which is sorted as a number. Would this cover all cases?

**Comment by jbbjarnason** [comment]
@SindriTh  I am a bit confused, do numbers not get sorted while being a part of the name,

Here is another example:

![image](https://github.com/Skaginn3x/framework/assets/15651464/01b54525-9498-482a-aa10-8377d06cfc78)

**Comment by SindriTh** [comment]
I will look into this.

However, please note that
```
atv320_i7
atv320_i8
atv320_i9
atv320_i10
```
would alphabetically sort to 
```
atv320_i10
atv320_i7
atv320_i8
atv320_i9
```
due to 1 being "earlier in the alphabet" than 7.

This is clearly not the issue here but will be something that we will have to solve

**Comment by jbbjarnason** [comment]
this is better but still weird

![image](https://github.com/Skaginn3x/framework/assets/15651464/c087247a-d97e-41dc-834c-58080f016280)
