### ISSUE TITLE
vcpkg pin versioning

### ISSUE THREAD

**Issue by jbbjarnason** [Skaginn3x/framework#393]
Pinning version has the benefit of being able to recompile the same binary at any given time, it would be useful if debugging crashes when necessary.

Please review this link: https://learn.microsoft.com/en-us/vcpkg/users/versioning#overrides

Mind that dependencies of dependencies need to be pinned.

**Comment by jbbjarnason** [comment]
vcpkg-sysroot (405-glaze-tagged-variant-const-missing)> cat vcpkg/status

**Comment by omarhogni** [comment]
We will use coredumps and symbol files for now see #394
