### ISSUE TITLE
0 shows at empty configurator

### ISSUE THREAD

**Issue by jbbjarnason** [Skaginn3x/framework#462]
![image](https://github.com/Skaginn3x/framework/assets/15651464/e2bace58-5a9c-4767-8fbe-3ba834224845)

**Comment by jbbjarnason** [comment]
This requires to always put 0 in if changing speed for example. need to fix asap

**Comment by SindriTh** [comment]
Description unsatisfactory, Does inductance and resistance not auto populate with 0?

**Comment by jbbjarnason** [comment]
You can login to target and try to write 0
