### ISSUE TITLE
Look into reading analog inputs from ATV320 periodically or by increasing the PDO size

### ISSUE THREAD

**Issue by omarhogni** [Skaginn3x/framework#538]

**Comment by omarhogni** [comment]
This is not possible


![Image](https://github.com/Skaginn3x/framework/assets/70097935/61cf0442-a579-4cf4-a543-cca85c8ab479)

**Comment by omarhogni** [comment]
@jbbjarnason How do you want to proceed?

**Comment by jbbjarnason** [comment]
The options I see valid:
- Accept sdo read being blocking and poll on interval greater than 1s, and hope for the best 
- Somehow implement async sdo read in soem
- Use Rust
- Use Lenze

I think the least work would be using Lenze.
I would like to research how much effort adding async functionality to soem before answering.

**Comment by omarhogni** [comment]
Let's plan on using lenze for now, I will close this issue as complete and add a task to implement a proper lenze driver inside of tfc.
