### ISSUE TITLE
Host debian package of framework somewhere

### ISSUE THREAD

**Issue by jbbjarnason** [Skaginn3x/framework#89]
This is needed for testing installation of subpackages, example of failure:

![MicrosoftTeams-image](https://github.com/Skaginn3x/framework/assets/15651464/2cb556a0-c258-4812-b6ef-cb9cb742a141)

**Comment by omarhogni** [comment]
Does cloudsmith solve this use case @jbbjarnason  ?

**Comment by jbbjarnason** [comment]
closed in favor of https://github.com/Skaginn3x/framework/pull/147

might still need to document how to add the repo on any debian based distro
